# Site Settings
lang: en
title: Spatial Analysis with R and Python
tagline: Material for Labs - Spatial Econometrics Advanced Institute 2022
email: vincnardelli@gmail.com
description: Spatial Analysis with R and Python - Material for Labs - Spatial Econometrics Advanced Institute 2022
fixed_navbar: top
remote_theme:  chrisrhymes/bulma-clean-theme 
