# Site Settings
lang: en
title: Spatial Analysis with Python
tagline: Material for Python Labs - Spatial Econometrics Advanced Institute 2021
email: vincnardelli@gmail.com
description: Material for Python Labs - Spatial Econometrics Advanced Institute 2021
fixed_navbar: top
remote_theme:  chrisrhymes/bulma-clean-theme 
